export type Brand<K, T> = K & { __brand: T }

export type StudentId = Brand<string, "StudentId">
export function createStudentId(value: string){
  if (/^STU\d{6}$/.test(value)) { // Must start with STU, \d enforces 6 digits, $ end of string
    return value as StudentId
  }
  return new Error('Invalid StudentId: "${value}"')
}
  

export type CourseCode = Brand<string, "CourseCode">
export function createCourseCode(value: string){
  if (/^[A-Z]{2,4}\d{3}$/.test(value)) { // [A-Z]{2. 4} 2-4 uppercase, \d{3} enforces 3 digits, $ end
    return value as CourseCode
  }
  return new Error(`Invalid CourseCode: "${value}"`)
}

export type Email = Brand<string, "Email">
export function createEmail(value: string){
  if (/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)){ // Generated by Codex
  /*
  explanation of the email regex
  ^           → start
  [^\s@]+     → one or more chars that are NOT space or @  (the username)
  @           → literal @
  [^\s@]+     → one or more chars that are NOT space or @  (the domain)
  \.          → literal dot
  [^\s@]+     → one or more chars (the TLD, e.g. "fr", "com")
  $           → end
  Matches: alice@epita.fr — Rejects: alice, alice@, alice@epita
  */
    return value as Email
  }
    return new Error('Invalid Email: "${value}"')
}

export type Credits = Brand<number, "Credits">
const valid_credits = [1, 2, 3, 4, 6] as const
export function createCredits(value: number){
  if ((valid_credits as readonly number[]).includes(value)){
    return value as Credits
  }
  return new Error("Invalid Credits: ${value} (must be 1, 2, 3, 4, or 6)")
}

export type Semester = Brand<string, "Semester">
export function createSemester(value: string){
  if (/^(Fall|Spring|Summer)\d{4}$/.test(value)){
    return (value as Semester)
  }
  return new Error('Invalid Semester: "${value}"')
}

export type EnrollmentId = Brand<string, "EnrollmentId">
export function createEnrollmentId(value: string){
  if (/^ENR.+$/.test(value)){ // .+ one or more of any char
    return (value as EnrollmentId)
  }
  return new Error('Invalid EnrollmentId: "${value}"')
}
