export type Brand<K, T> = K & { __brand: T };

// Student id
export type StudentId = Brand<string, "StudentId">;
export function createStudentId(value: string): StudentId | Error {
  return /^STU\d{6}$/.test(value) // Must start with STU, \d enforces 6 digits, $ end of string
    ? (value as StudentId)
    : new Error(`Invalid StudentId: "${value}"`);
}

// Course Code
export type CourseCode = Brand<string, "CourseCode">;
export function createCourseCode(value: string): CourseCode | Error {
  return /^[A-Z]{2,4}\d{3}$/.test(value) // [A-Z]{2. 4} 2-4 uppercase, \d{3} enforces 3 digits, $ end
    ? (value as CourseCode)
    : new Error(`Invalid CourseCode: "${value}"`);
}

// email
export type Email = Brand<string, "Email">;
export function createEmail(value: string): Email | Error {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value) // Generated by Codex
  /*
  explanation of the email regex
  ^           → start
  [^\s@]+     → one or more chars that are NOT space or @  (the username)
  @           → literal @
  [^\s@]+     → one or more chars that are NOT space or @  (the domain)
  \.          → literal dot
  [^\s@]+     → one or more chars (the TLD, e.g. "fr", "com")
  $           → end
  Matches: alice@epita.fr — Rejects: alice, alice@, alice@epita
  */
    ? (value as Email)
    : new Error(`Invalid Email: "${value}"`);
}

// credits
export type Credits = Brand<number, "Credits">;
const VALID_CREDITS = [1, 2, 3, 4, 6] as const;
export function createCredits(value: number): Credits | Error {
  return (VALID_CREDITS as readonly number[]).includes(value)
    ? (value as Credits)
    : new Error(`Invalid Credits: ${value} (must be 1, 2, 3, 4, or 6)`);
}

// semester
export type Semester = Brand<string, "Semester">;
export function createSemester(value: string): Semester | Error {
  return /^(Fall|Spring|Summer)\d{4}$/.test(value)
    ? (value as Semester)
    : new Error(`Invalid Semester: "${value}"`);
}

// enrollment id
export type EnrollmentId = Brand<string, "EnrollmentId">;
export function createEnrollmentId(value: string): EnrollmentId | Error {
  return /^ENR.+$/.test(value) // .+ one or more of any char
    ? (value as EnrollmentId)
    : new Error(`Invalid EnrollmentId: "${value}"`);
}
